name: Build Native Executables Only

on:
  workflow_dispatch: # Manual triggering only
  push:
    branches: [ develop, feature/* ] # Build on feature branches

permissions:
  contents: read

jobs:
  build-native-windows:
    name: Build Windows Native Executable
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Native Image
        run: gu install native-image

      - name: Gradle wrapper perms
        run: chmod +x gradlew

      - name: Build Windows Native Executable
        run: ./gradlew nativeCompile

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TheLegendOfBelga-Windows
          path: build/native/nativeCompile/TheLegendOfBelga.exe
          retention-days: 30

  build-native-linux:
    name: Build Linux Native Executable
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Native Image
        run: gu install native-image

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libz-dev zlib1g-dev

      - name: Gradle wrapper perms
        run: chmod +x gradlew

      - name: Build Linux Native Executable
        run: ./gradlew nativeCompile

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TheLegendOfBelga-Linux
          path: build/native/nativeCompile/TheLegendOfBelga
          retention-days: 30

  build-native-macos:
    name: Build macOS Native Executable
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Native Image
        run: gu install native-image

      - name: Gradle wrapper perms
        run: chmod +x gradlew

      - name: Build macOS Native Executable
        run: ./gradlew nativeCompile

      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TheLegendOfBelga-macOS
          path: build/native/nativeCompile/TheLegendOfBelga
          retention-days: 30
